package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Saturday, 9 May, 2026 4:36:38 PM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
} // interface CalculatorOperations
