package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, 10 May, 2026 5:39:40 PM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int sub (int a, int b);
} // interface CalculatorOperations
