package PrimeApp;


/**
* PrimeApp/Prime.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Saturday, 9 May, 2026 11:45:57 PM IST
*/

public interface Prime extends PrimeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Prime
