package PrimeApp;


/**
* PrimeApp/PrimeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Prime.idl
* Saturday, 9 May, 2026 11:45:57 PM IST
*/

public interface PrimeOperations 
{
  String checkPrime (int n);
} // interface PrimeOperations
