package OddEvenApp;


/**
* OddEvenApp/OddEvenOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OddEven.idl
* Saturday, 9 May, 2026 10:46:40 PM IST
*/

public interface OddEvenOperations 
{
  String check (int n);
} // interface OddEvenOperations
