package OddEvenApp;


/**
* OddEvenApp/OddEven.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from OddEven.idl
* Saturday, 9 May, 2026 10:46:40 PM IST
*/

public interface OddEven extends OddEvenOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OddEven
