package StringApp;


/**
* StringApp/StringOperationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringOp.idl
* Saturday, 9 May, 2026 10:19:48 PM IST
*/

public interface StringOperationOperations 
{
  String reverse (String str);
} // interface StringOperationOperations
